'use strict';
const M=DemoModel,candles=M.createCandles();
let language='en',groups=[],selectedMinute=36;
const el=id=>document.getElementById(id);
const messages={
 en:{synthetic:'SYNTHETIC DEMO',code:'View code ↗',eyebrow:'A PERSONAL SURVEILLANCE EXPERIMENT',title:'Follow the signal. Check the data.',intro:'Select an event to see the minute, the calculation and the source values together.',generated:'Generated data · no live feed',disclosure:'Every price and volume on this page is invented. This sample shows a review workflow; it does not identify traders or prove market abuse.',market:'MARKET CONTEXT',candles:'candles',price:'Price',volume:'Quote volume',eventMarkers:'Review events',chartTip:'Gold markers link the chart to the event list below. The highlighted minute is the one you are reviewing.',events:'Events to review',empty:'No events at these thresholds. Lower a threshold or reset the sample.',evidence:'EVIDENCE',why:'Why this minute?',download:'Download synthetic evidence ↓',exportNote:'JSON includes this minute, its previous 20 minutes and the rule calculations.',tryThresholds:'Try different thresholds',localOnly:'Changes apply to this sample only',volumeThreshold:'R04 · Volume multiple',sideThreshold:'R05 · Dominant side',reset:'Reset sample',thresholdNote:'Changing a threshold changes the number of alerts. It does not tell us whether those alerts are useful or accurate.',footer:'Independent personal project · two illustrative rules · no account data',privacy:'Data & privacy ↗',spike:'Volume spike',buy:'Buy-side dominance',sell:'Sell-side dominance',minuteVolume:'This minute',baseline:'Prior 20-minute median',threshold:'Threshold',buyVolume:'Buy-initiated volume',sellVolume:'Sell-initiated volume',volumeExplain:'Quote volume is compared with the previous 20 minutes. The current minute is excluded from the baseline.',sideExplain:'Share of quote volume attributed to the initiating side in this generated minute.',boundary:'A price-and-volume signal gives a reason to review the data. It does not establish identity or intent.',noSelection:'Choose an event to inspect its values.',alerts:'alerts',eventWord:'events',volumeAxis:'VOLUME · USDT',chartLabel:'Generated minute candles and quote volume. Select a numbered event to inspect its evidence.',inspect:'Inspect event',syntheticMinute:'Synthetic minute'},
 ru:{synthetic:'СИНТЕТИЧЕСКОЕ ДЕМО',code:'Исходный код ↗',eyebrow:'ЛИЧНЫЙ ПРОЕКТ ПО НАБЛЮДЕНИЮ ЗА РЫНКОМ',title:'От сигнала — к исходным данным.',intro:'Выберите событие: график, расчёт и исходные значения окажутся рядом.',generated:'Сгенерированные данные · без биржи',disclosure:'Все цены и объёмы на этой странице выдуманы. Пример показывает процесс проверки; он не определяет участников торгов и не доказывает манипуляции.',market:'КОНТЕКСТ РЫНКА',candles:'свечи',price:'Цена',volume:'Объём в USDT',eventMarkers:'События',chartTip:'Золотые метки связаны со списком событий ниже. Выделена минута, которую вы сейчас проверяете.',events:'События для проверки',empty:'При этих порогах событий нет. Уменьшите порог или сбросьте настройки.',evidence:'ИСХОДНЫЕ ЗНАЧЕНИЯ',why:'Почему эта минута?',download:'Скачать синтетические данные ↓',exportNote:'JSON содержит эту минуту, предыдущие 20 минут и расчёты правил.',tryThresholds:'Попробовать другие пороги',localOnly:'Настройки только для этого примера',volumeThreshold:'R04 · Кратность объёма',sideThreshold:'R05 · Преобладающая сторона',reset:'Сбросить настройки',thresholdNote:'Порог меняет число сигналов. Это ещё не говорит об их полезности или точности.',footer:'Личный независимый проект · два правила для примера · без данных аккаунтов',privacy:'Данные и приватность ↗',spike:'Всплеск объёма',buy:'Преобладают покупки',sell:'Преобладают продажи',minuteVolume:'Объём этой минуты',baseline:'Медиана предыдущих 20 минут',threshold:'Порог',buyVolume:'Объём по инициатору: покупка',sellVolume:'Объём по инициатору: продажа',volumeExplain:'Сравниваем объём с предыдущими 20 минутами. Текущая минута не входит в базу сравнения.',sideExplain:'Доля объёма со стороны инициатора сделки в этой сгенерированной минуте.',boundary:'Изменения цены и объёма дают повод проверить данные. Они не устанавливают личность и намерения участника.',noSelection:'Выберите событие, чтобы посмотреть расчёт.',alerts:'сигналов',eventWord:'событий',volumeAxis:'ОБЪЁМ · USDT',chartLabel:'Сгенерированные минутные свечи и объёмы. Выберите событие с номером, чтобы посмотреть расчёт.',inspect:'Открыть событие',syntheticMinute:'Синтетическая минута'}
};
const t=key=>messages[language][key];
const fmt=(n,d=0)=>n.toLocaleString(language==='ru'?'ru-RU':'en-US',{maximumFractionDigits:d,minimumFractionDigits:d});
const time=value=>value.slice(11,16);
const plural=(n,one,few,many)=>n%100>=11&&n%100<=14?many:n%10===1?one:n%10>=2&&n%10<=4?few:many;
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const thresholds=()=>({volumeMultiple:Number(el('volumeThreshold').value),sidePercent:Number(el('sideThreshold').value)});
function alertName(alert){return alert.rule==='R04'?t('spike'):t(alert.evidence.side);}
function choose(minute){selectedMinute=minute;renderEvents();renderInspection();renderChart();}
function update(){groups=M.groupAlerts(M.analyze(candles,thresholds()));if(!groups.some(g=>g.minute===selectedMinute))selectedMinute=groups[0]?.minute??null;el('volumeValue').textContent=el('volumeThreshold').value+'×';el('sideValue').textContent=el('sideThreshold').value+'%';renderEvents();renderInspection();renderChart();}
function renderEvents(){
 const count=groups.reduce((n,g)=>n+g.alerts.length,0);el('eventCount').textContent=language==='ru'?`${groups.length} ${plural(groups.length,'событие','события','событий')} · ${count} ${plural(count,'сигнал','сигнала','сигналов')}`:`${groups.length} events · ${count} alerts`;
 el('empty').hidden=groups.length>0;el('events').replaceChildren();
 groups.forEach((g,i)=>{const b=node('button',undefined,'event'+(g.minute===selectedMinute?' active':''));b.type='button';b.setAttribute('aria-pressed',String(g.minute===selectedMinute));b.setAttribute('aria-label',`${t('inspect')} ${i+1}, ${time(g.time)} UTC`);const head=node('div',undefined,'event-head');head.append(node('span',time(g.time)+' UTC'),node('span',String(i+1),'dot'));b.append(head,node('strong',g.alerts.map(alertName).join(' + ')),node('small',g.alerts.map(a=>a.rule).join(' · ')));b.onclick=()=>choose(g.minute);el('events').append(b);});
}
function values(rows){const list=node('dl',undefined,'values');for(const [key,value]of rows){const row=node('div');row.append(node('dt',key),node('dd',value));list.append(row);}return list;}
function renderInspection(){
 const group=groups.find(g=>g.minute===selectedMinute),target=el('inspection');target.replaceChildren();el('download').setAttribute('aria-disabled',String(!group));el('download').removeAttribute('href');
 if(group){el('download').href='data:application/json;charset=utf-8,'+encodeURIComponent(JSON.stringify(M.evidenceBundle(candles,group,thresholds()),null,2));el('download').download=`synthetic-event-${group.minute}.json`;}
 el('eventNumber').textContent=group?String(groups.indexOf(group)+1).padStart(2,'0'):'—';
 if(!group){target.append(node('p',t('noSelection'),'boundary'));return;}
 const meta=node('p',undefined,'inspect-meta');meta.append(node('strong',time(group.time)+' UTC · '+M.SYMBOL),node('br'),node('span',t('syntheticMinute')+' · 15 Jan 2026'));target.append(meta);
 for(const alert of group.alerts){const section=node('section',undefined,'rule'),head=node('div',undefined,'rule-head');head.append(node('span',alertName(alert),'rule-name'),node('span',alert.rule,'rule-badge'));section.append(head);
  const calc=node('p',undefined,'calculation');calc.append(node('span',fmt(alert.value,1)+(alert.rule==='R04'?'×':'%')),node('small',' / '+t('threshold')+' '+fmt(alert.threshold)+(alert.rule==='R04'?'×':'%')));section.append(calc);
  if(alert.rule==='R04')section.append(node('p',t('volumeExplain'),'rule-explain'),values([[t('minuteVolume'),fmt(alert.evidence.quoteVolume,2)+' USDT'],[t('baseline'),fmt(alert.evidence.baseline,2)+' USDT']]));
  else section.append(node('p',t('sideExplain'),'rule-explain'),values([[t('buyVolume'),fmt(alert.evidence.buyQuoteVolume,2)+' USDT'],[t('sellVolume'),fmt(alert.evidence.sellQuoteVolume,2)+' USDT']]));
  target.append(section);
 }
 target.append(node('p',t('boundary'),'boundary'));
}
const NS='http://www.w3.org/2000/svg';
function svgNode(tag,attrs={},text){const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;return n;}
function renderChart(){
 const svg=svgNode('svg',{viewBox:'0 0 900 374',role:'group','aria-label':t('chartLabel')}),left=44,right=822,top=48,bottom=228,width=right-left,step=width/candles.length;
 const low=Math.min(...candles.map(c=>c.low))-.15,high=Math.max(...candles.map(c=>c.high))+.35;
 const x=i=>left+(i+.5)*step,y=p=>bottom-(p-low)/(high-low)*(bottom-top),maxVolume=Math.max(...candles.map(c=>c.quoteVolume));
 if(selectedMinute!==null)svg.append(svgNode('rect',{x:x(selectedMinute)-step/2,y:top-14,width:step,height:304,fill:'#f5e6c9'}));
 for(let i=0;i<5;i++){const price=low+(high-low)*i/4,yy=y(price);svg.append(svgNode('line',{x1:left,x2:right,y1:yy,y2:yy,stroke:'#e9edf2'}),svgNode('text',{x:right+10,y:yy+4,fill:'#7b8798','font-size':11},fmt(price,2)));}
 candles.forEach(c=>{const color=c.close>=c.open?'#158273':'#c56369',bodyTop=Math.min(y(c.open),y(c.close)),height=Math.max(1.5,Math.abs(y(c.close)-y(c.open)));svg.append(svgNode('line',{x1:x(c.index),x2:x(c.index),y1:y(c.high),y2:y(c.low),stroke:color,'stroke-width':1}),svgNode('rect',{x:x(c.index)-step*.28,y:bodyTop,width:step*.56,height,fill:color}));const h=c.quoteVolume/maxVolume*60,buyH=h*c.buyQuoteVolume/c.quoteVolume;svg.append(svgNode('rect',{x:x(c.index)-step*.3,y:342-h,width:step*.6,height:h-buyH,fill:'#daa7ab'}),svgNode('rect',{x:x(c.index)-step*.3,y:342-buyH,width:step*.6,height:buyH,fill:'#8dbfb7'}));});
 svg.append(svgNode('text',{x:left,y:271,fill:'#7b8798','font-size':9,'letter-spacing':1},t('volumeAxis')),svgNode('text',{x:right+10,y:286,fill:'#7b8798','font-size':10},fmt(maxVolume/1000000,1)+'m'),svgNode('text',{x:right+10,y:346,fill:'#7b8798','font-size':10},'0'));
 for(const i of [0,24,48,72,95])svg.append(svgNode('text',{x:x(i),y:365,'text-anchor':'middle',fill:'#7b8798','font-size':11},time(candles[i].time)));
 svg.append(svgNode('text',{x:right+10,y:365,fill:'#7b8798','font-size':10},'UTC'));
 groups.forEach((g,i)=>{const xx=x(g.minute),yy=y(candles[g.minute].high)-21,mark=svgNode('g',{class:'marker',role:'button',tabindex:0,'aria-label':`${t('inspect')} ${i+1}, ${time(g.time)} UTC`});mark.append(svgNode('line',{x1:xx,x2:xx,y1:yy+12,y2:342,stroke:'#d7aa55','stroke-dasharray':'3 4','stroke-width':1,opacity:.75}),svgNode('circle',{cx:xx,cy:yy,r:12,fill:g.minute===selectedMinute?'#bd8b30':'#d7aa55',stroke:'#fff','stroke-width':2}),svgNode('text',{x:xx,y:yy+4,'text-anchor':'middle',fill:'white','font-size':11,'font-weight':600},String(i+1)));mark.onclick=()=>choose(g.minute);mark.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(g.minute);}};svg.append(mark);});
 el('chart').replaceChildren(svg);
}
function translate(){document.documentElement.lang=language;document.querySelectorAll('[data-i18n]').forEach(n=>n.textContent=t(n.dataset.i18n));el('language').textContent=language==='en'?'RU':'EN';el('language').setAttribute('aria-label',language==='en'?'Переключить на русский':'Switch to English');update();}
el('language').onclick=()=>{language=language==='en'?'ru':'en';translate();};
el('volumeThreshold').oninput=update;el('sideThreshold').oninput=update;
el('reset').onclick=()=>{el('volumeThreshold').value='5';el('sideThreshold').value='80';selectedMinute=36;update();};

translate();
